### ISSUE TITLE
DateController always validates all rules

### ISSUE THREAD

**Issue by timgent** [UKHomeOffice/brp_enquiry_forms#249]
Regardless of which validators are specified in "fields", DateController will always do validation against isEmpty, isInvalidChars, isInvalidDateFormat, isFutureDate.

Ideally it would validate against the rules specified in fields.

Note this doesn't currently cause any harmful behaviour in the application, as the validations are needed for it. But if we are going to split this out and put it into HOF then it would be good for it to be more generic.

**Comment by JoeChapman** [comment]
@timgent is this still an issue or can it be closed?

**Comment by easternbloc** [comment]
@timgent @JoeChapman Is this still an issue? I'd like to move it to hof-controllers if so...
